#!/bin/bash

function FslMask_help
{
    echo
    echo "FslMask.bash [OPTIONS] Subject1 Subject2 ... SubjectN"
    echo
    echo "FSL functions used:  None"
    echo "AFNI functions used: 3dAutomask, 3dmak_tool"
    echo
    echo "USAGE:"
    echo
    echo "The purpose of this script is to create a binary mask for any number of 4D fMRI"
    echo "images that are typically separated into run directories. Afni's 3dAutomask generates"
    echo "the masks and dilates them by 1 voxel. A compositive mask is generated by taking the"
    echo "intersection of all the masked runs found and placed one directory level above"
    echo "the run directories."
    echo
    echo "OPTIONS:"
    echo "  -M SubjectMaster    directory to scan for subjects"
    echo "                      DEFAULT: Subjects"
    echo "  -N CompositName     name to give compositive mask which is the intersection of all"
    echo "                      the masked runs. If your runs are separated into task folders,"
    echo "                      which I encourage you should do, a good name is the task name."
    echo "                      For example: MidMask or SocialMask"
    echo "                      REQUIRED"
    echo "  -U UserEmail        email address mailed when job finished"
    echo "                      DEFAULT: `whoami`@umich.edu"
    echo "  -f SubDirectory     directory to run directories or files, search directly below subject directory"
    echo "                      DEFAULT: func"
    echo "  -r RunDirectory     text to search for run directories"
    echo "                      if using a wild card expression, surround it with single quotes"
    echo "                      for example: 'run*nii'"
    echo "                      DEFAULT: run*"
    echo "  -v VolumeSearch     text to search for volumes"
    echo "                      if using a wild card expression, surround it with single quotes"
    echo "                      for example: 'ra_spm8_run*nii'"
    echo '                      DEFAULT: s8w2mm_fsl_rarun*nii'
    echo
}

if (( $# == 0 ))
then
    FslMask_help
    exit
fi

# set some variables
SubjectMaster=Subjects
CompositeName=
CompositeFlag=false
UserEmail=`whoami`@umich.edu
SubDirectory=func
RunDirectory='run*'
VolumeSearch='s8fsl_w2mm_rarun*nii'

# parse the arguments
while (( $# > 0 ))
do
    while getopts M:N:U:f:r:v:h opt
    do
        case "$opt" in
            h)
                FslMask_help
                exit
                ;;
            M)
                SubjectMaster=${OPTARG}
                ;;
            N)
                CompositeName=${OPTARG}
                CompositeFlag=true
                ;;
            U)
                UserEmail=${OPTARG}
                ;;
            f)
                SubDirectory=${OPTARG}
                ;;
            r)
                RunDirectory=${OPTARG}
                ;;
            v)
                VolumeSearch=${OPTARG}
                ;;
        esac
    done

    shift $((OPTIND-1))
    OPTIND=0

    # assume arguments with no flags are subjects
    if [ $# -gt 0 ]
    then
        let nSubjects++
        subjects[${nSubjects}]=$1
        shift
    fi
done

# check if Composite was assigned
if [ "$Composite" = false ]
then
    echo
    echo "Composite name not specified."
    echo "You can specifiy this with the -N flag."
    echo "Read the help for additional information."
    echo "* * * A B O R T I N G * * *"
    exit
fi

# make sure subjects were specified
if [ ${#subjects[@]} -eq 0 ]
then
    echo
    echo "No subjects specified."
    echo ' * * * A B O R T I N G * * *'
    echo
    exit
fi

# check if master directory exists
MasterDir=`pwd`/${SubjectMaster}
if [ ! -d ${MasterDir} ]
then    
    echo
    echo "Directory ${MasterDir} does not exist."
    echo "Check your -M flag."
    echo " * * * A B O R T I N G * * *"
    echo
    exit
fi

# do file checking for all subjects
for iSubject in "${subjects[@]}"
do

    # check if subject directory is present
    if [ ! -d ${MasterDir}/${iSubject} ]
    then
        echo
        echo "Subject directory ${iSubject} does not exist."
        echo ' * * * A B O R T I N G * * *'
        echo
        exit
    fi

    # check if func directory is present
    FullDirec=${MasterDir}/${iSubject}/${SubDirectory}
    if [ ! -d ${FullDirec} ]
    then
        echo
        echo "Looked for directory ${FullDirec} but it was not found."
        echo "Check -f option."
        echo ' * * * A B O R T I N G * * * '
        echo
        exit
    fi

    # check run directory
    RunDirec=(`ls -d ${FullDirec}/${RunDirectory}`)
    if [ -z "$RunDirec" ]
    then
        echo
        echo "No run directories found in ${FullDirec}"
        echo "Used regex '${RunDirectory}'"
        echo "Check -r option"
        echo " * * * A B O R T I N G * * *"
        exit
    fi

    for oneRun in "${RunDirec[@]}"
    do
        # check if directory exists
        if [ ! -d ${oneRun} ]
        then
            echo
            echo "Run directory ${oneRun} does not exist"
            echo "Check -r option."
            echo " * * * A B O R T I N G * * *"
            echo
            exit
        fi

        # check if directory contains run files
        RunFiles=(`ls -d ${oneRun}/${VolumeSearch}`)
        if [ ${#RunFiles[@]} -eq 0 ]
        then
            echo
            echo "Subject ${iSubject} has no files to warp."
            echo "Looked in ${RunDirec} with regex '${VolumeSearch}'"
            echo "Check -v option"
            echo " * * * A B O R T I N G * * *"
            echo
            exit
        else
            RunName=`basename ${oneRun}`
            echo "Subject : ${iSubject}/${RunName} found ${#RunFiles[@]} run(s)"
        fi
    done
done

# all subjects should be good, now we do actual work
for iSubject in "${subjects[@]}"
do
    # grab files again
    FuncDirec=${MasterDir}/${iSubject}/${SubDirectory}
    RunDirs=(`ls -d ${FuncDirec}/${RunDirectory}`)

    # mask images
    for iRun in "${RunDirs[@]}"
    do
        MaskFiles=(`ls -d ${iRun}/${VolumeSearch}`)
        for iWarpFile in "${MaskFiles[@]}"
        do
            TopDir=`dirname ${iWarpFile}`
            FileName=`basename ${iWarpFile}`
            3dAutomask -overwrite -prefix ${TopDir}/mask_${FileName} -dilate 1 ${iWarpFile}
        done
    done

    # make composite mask
    3dmask_tool -input `ls -d ${FuncDirec}/${RunDirectory}/mask_${VolumeSearch}` \
        -prefix ${FuncDirec}/${CompositeName}.nii -frac 1.0 -overwrite
done

EndTime=`date`
# mail when all are finished
mail -s 'FslMask.bash' ${UserEmail} <<EOF
Start: ${StartTime}
End  : ${EndTime}

Masked ${#subjects[@]} subjects
EOF
    
